### ISSUE TITLE
Feature request - Estimated Energy/Year

### ISSUE THREAD

**Issue by ECort** [gruijter/com.gruijter.powerhour#115]
High Robin,
You've built a super generic app to monitor energy usage! Many thanks.

I've a feature request: 
Would it be possible to estimate year consumption? Maybe like: used energy current year/measured day's current year * 365?

It would provide insight / estimate in the year consumption immediately after installing a smart energy monitor.

Kind regards,
Eric

**Comment by gruijter** [comment]
since many people have a non-linear usage distribution over the year, it is very hard to create a yearly usage prediction. There is however already a function very similar to what you want that does take distribution into account. It is the budget function (see advanced device settings). So with some fiddling you might be able to use that for what you want to achieve.

**Comment by ECort** [comment]
Hi Robin,
Very true. Found the 'budget' function and will use it. 

Thanks for the reply.
Kind regards,
Eric
