### ISSUE TITLE
Source device remains missing after Homey boot

### ISSUE THREAD

**Issue by franklovas** [gruijter/com.gruijter.powerhour#12]
Hi. I restart my Homey once a week, and every time I do this the app crashes. To get it working again I have to go to apps, choose the app, go to settings and restart the app. Is this a known issue?

**Comment by gruijter** [comment]
Not a kniwn issue. Is the app really crashing? In that case I should already automatically receive crash reports from you. But I dont get these. So I think you mean something else. Maybe the devices are temporarely available? See the forum for explaination on that topic. Otherwise pls send an app diagnostics report with a note what exactly is not working acfcording to you.

**Comment by franklovas** [comment]
I have just restarted Homey, and created a report.

9eeda769-71bc-4f91-8fad-e2824c61742f

![image](https://user-images.githubusercontent.com/47778031/146928050-28883625-8354-4e73-b246-6aac1054946d.png)

**Comment by gruijter** [comment]
In the diagnostics report I see the source device is missing (or not ready yet)

Did you see this forum post and did you wait an hour after reboot?

https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/401?u=gruijter

**Comment by franklovas** [comment]
I may have been a bit impasient, i will wait one hour and see if the notification goes away.

**Comment by franklovas** [comment]
Hi, i have waited now for about 2 hours, And the device are still unavailable after a Homey boot.

**Comment by gruijter** [comment]
should be solved in current release.
