### ISSUE TITLE
Power by the Hour returns true when it has to be false

### ISSUE THREAD

**Issue by Chris-L-Nederland** [gruijter/com.gruijter.powerhour#123]
Hi Robin,

Yesterday and today Power by the Hour returns true while it has to be false.
Today the card "Prijs is een van de 2 laagste van vandaag" turned true at 13:00 and it should be 14:00 and 15:00 in the Netherlands.
I think it does this when the price is under 0.
I hope you can help me to solve this.

Thanks in advance,
Chris.

**Comment by Chris-L-Nederland** [comment]
I love your app by the way :-)

**Comment by gruijter** [comment]
I cannot reproduce the issue. Do you still see the issue? How did you test for this?

**Comment by Chris-L-Nederland** [comment]
I used the following card:
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/134781284/f4ea805c-ef63-4bca-984e-054719e2ae40)
And when "Uren Te Laden" is 1 and "Aantal Uur Voor 7 uur" is i.e. 17 then it should choose the cheapest hour before 7 o' clock.
But it turned true 1 hour before and stopped 2 hours after. Those where the hours that the price was below zero.

**Comment by gruijter** [comment]
I looked into the code and cannot find any issue. Negative pricing should not impact it. It might be caused when the lowest prices are all exactly the same. It could also be caused by the prices for tomorrow not being available yet when you run the flow. You are using the flowcard outside of its specification:
Aantal (number) should be between 1 - 8
Periode (period) should be between 2 - 12

And are you sure the used tags have the values you think they have?
I'm not saying it surely doesn't work when using the numbers you are using, but chances are that 17 hours before 7am (=2pm) the prices for tomorrow are not available yet in PBTH.

**Comment by Chris-L-Nederland** [comment]
I wasn't aware of the specs; then that will be the reason that the results are different than I expected.
I'm going to see if I can solve my use case in a different way.
Thank you so much for your effort.

Still loving your app :)

**Comment by gruijter** [comment]
Super, thx!
