### ISSUE TITLE
The card "New prices for today/tomorrow" is not triggered 

### ISSUE THREAD

**Issue by emilkola** [gruijter/com.gruijter.powerhour#133]
Since a couple of days the card "New prices for today/tomorrow" is not triggered when new prices is avaiable. 
I use that card and the JSON with prices in my logic for many things, could you please have a look?

**Comment by Allectra** [comment]
The prices have also not been updated since yesterday 15/7

**Comment by HUM65** [comment]
Same issue here, wanna use this but it seems that it doesn't trigger. And yes prices are changed.

**Comment by gruijter** [comment]
Yes. Is a problem. Will solve it in next release. Have patience pls ❤️

**Comment by wimpy61** [comment]
Has this problem been solved in 5.6.7, as i am on this version but still same problem

**Comment by gruijter** [comment]
Nope, not yet. I do this in my spare time. It appears I have little time to spare lately...

**Comment by wimpy61** [comment]
No problem, appreciate the work!

**Comment by gruijter** [comment]
Should be fixed in v5.6.9: https://homey.app/a/com.gruijter.powerhour/test/
Please test and let me know.

**Comment by wimpy61** [comment]
Hey Robin,Na installatie kreeg ik direct de prijzen voor morgen weer te zien, dus dat lijkt gefixed.Heb ook nog wat flows lopen, ik kijk morgen even of die ook weer werken.In ieder geval bedankt zover.GroetjesWim
-------- Oorspronkelijk bericht --------Van: gruijter ***@***.***> Datum: 04-08-2023  16:15  (GMT+01:00) Aan: "gruijter/com.gruijter.powerhour" ***@***.***> Cc: wimpy61 ***@***.***>, Comment ***@***.***> Onderwerp: Re: [gruijter/com.gruijter.powerhour] The card "New prices for today/tomorrow" is not triggered  (Issue #133) 
Should be fixed in v5.6.9: https://homey.app/a/com.gruijter.powerhour/test/
Please test and let me know.

**Comment by wimpy61** [comment]
Hey Robin,Alles werkt naar behoren!Krijg keurig berichtjes met de prijzen van morgen en ook een extra waarschuwing als de prijs negatief is ivm zonnepanelen.Helemaal top, dankjewel voor de moeite.Met vriendelijke groetWim
-------- Oorspronkelijk bericht --------Van: gruijter ***@***.***> Datum: 04-08-2023  16:15  (GMT+01:00) Aan: "gruijter/com.gruijter.powerhour" ***@***.***> Cc: wimpy61 ***@***.***>, Comment ***@***.***> Onderwerp: Re: [gruijter/com.gruijter.powerhour] The card "New prices for today/tomorrow" is not triggered  (Issue #133) 
Should be fixed in v5.6.9: https://homey.app/a/com.gruijter.powerhour/test/
Please test and let me know.

**Comment by HUM65** [comment]
Yep, it is indeed working well,… thnx
