### ISSUE TITLE
Possibility to replace the underlying device without loosing data

### ISSUE THREAD

**Issue by StevenRenders** [gruijter/com.gruijter.powerhour#151]
I'm wondering if there is any way to replace the underlying device without loosing all statistics.
E.g. if a power plug fails and needs to be replaced.

There should be a maintenance option to attach to a different device.

Thanks,
Steven

**Comment by gruijter** [comment]
Implemented in new version 5.9.0: https://homey.app/a/com.gruijter.powerhour/test/

* Added repairing to a new source device.
* homey-api@3.1.0

This adds a feature that was requested by a number of people. You can now repair a summarizer to a new source device, e.g. because you deleted the source device in Homey. Repairing will keep all the Insights and Flows. But if you repair to a physically different source device the kWh meter will most likely jump. In that case you need to manually adjust the meter and money values in the advanced settings.

**Comment by Vetjes** [comment]
I seem to miss the setting for ‘this year start’ value in power. In gas it’s present. Casper Vet Op 18 nov 2023 om 21:39 heeft gruijter ***@***.***> het volgende geschreven:﻿
Closed #151 as completed.
