### ISSUE TITLE
X most expensive / cheap hours of the day

### ISSUE THREAD

**Issue by Zindar** [gruijter/com.gruijter.powerhour#25]
I'd like a card that allows me to trigger something on the X most expensive or cheap hours of the day.
So for example
For the three most expensive hours of the day I'd like to turn something of
For the four cheapest hours of the day, I'd like to run something extra (like charge my car)

So a card saying something like
"This is one of <number> most expensive hours of the day"

This can be one card with invert of course.

**Comment by Wouter-Berman** [comment]
In addition: it would be nice if this could be limited to: The X cheapest/most expensive hours of the day before [time].
I had programmed my boiler to heat in the cheapest hour of the day. Until I encountered the situation where on day 1 the cheapest hour was at 2 in the morning and on day 2 at 11 in the evening. Which resulted in a cold shower on day 2..
So programming something like Turn the boiler on if the current hour is among the 2 cheapest hours before 20:00 would be nice. But for charging a car you would probably want something like Charge the car in the 4 cheapest hours between 18:00 and 07:00.
Of course the last one is more challenging because the information for the following day is only available after 15:00 (?). Anyway, just a thought.

**Comment by gruijter** [comment]
_But for charging a car you would probably want something like Charge the car in the 4 cheapest hours between 18:00 and 07:00._

This can already be approximated now by adding a 'AND' in the flow (time is between 18.00 and 07.00) and triggering on cheapest 4 hours in the next 8 hours.

**Comment by Wouter-Berman** [comment]
The cheapest 4 hours in the next 8 hours is a sliding window criterium as it is evaluated every hour (correct?). In the following scenario I would wan the car to get charged between 02:00 and 06:00. Instead the car would not get charged at all.
![image](https://user-images.githubusercontent.com/73526294/171816313-4c4a9b9e-7748-4eef-a9e1-34f988e8389e.png)
Or do I misunderstand the trigger?

**Comment by gruijter** [comment]
Correct, it is sliding. But how would you suggest to automate your example? If you can come up with an all-situation-catching algorithm I would be very happy to implement it!

**Comment by Zindar** [comment]
Well, the car charging example might not have been the best. 

BUT.... if my car is normally set to charge between 18 and 07, but the car is already at home and connected at 15 and that happens to be cheaper than between 18 and 07, I would absolutely like to charge it.

A better example can be this.
In the 4 most expensive hours of the day, no matter when in the day, I'd like to turn down my house heating (or AC)
In the 4 cheapest hours of the day, no matter when in the day, I'd like to run it a little extra

What I personally will use this for is that I will turn off the heating of my pool during the most expensive hours.  Temperature in that large mass of water doesn't change fast so it's pretty safe to turn if off for a few hours every now and then.

**Comment by Wouter-Berman** [comment]
At any given time it is possible to evaluate the prices for the next 8 hours. That is because the prices for the next day are only available for sure at about 16:00. I guess that is why you limited your algorithm on 8 hours. Right?
But if we specify a starting time and an end time we have more possibilities. As long as the end time is higher than the starting time (start and end time are on the same day), we know we have a window of 24 hours which we can evaluate. Therefore, we can always evaluate whether the price of the current hour is among the X cheapest/most expensive hours between [hour start] and [hour end].
If the start time is higher than the end time (start time and end time are on two different days) we have to limit [hour start] to be between 16:00 and 23:00 (inclusive). In that case we can also always evaluate that the price of the current hour is among the X cheapest/most expensive hours between [hour start] and [hour end]. This does require us to retrieve not only the prices of the current day but also of the previous day.

**Comment by gruijter** [comment]
Yeah, implementing highest price, kind of inverted from the current lowest price triggers, is no problem. I just need timeto implement it.

The car scenario is indeed a different question and deserves a seperate issue/thread. But since we already started here lets just continue here.

**Comment by Zindar** [comment]
Going back to the car example anyway...

What I would like, is that when the car is connected in the evening, something will check the price from that time until 4 am, and will "mark" the cheapest hours somehow.  After that, for every hour, it will check if it's "marked" and start the charge if it is.

I had something similar as a homeyscript for a while, using the tibber api, but I have then moved from tibber so I can't use that API. (for anyone who doesn't know, tibber is an electricity company that has apis you can use if you are their customer)

**Comment by Wouter-Berman** [comment]
You have already written an algorithm for the cheapest hour of the day. Which is a special case of the car charging example specified as
If the current hour is among the [1] cheapest hours between 00:00 and 23:00 (inclusive). So the required algorithm would only need a slight modification of that one.

**Comment by Zindar** [comment]
ignore my "mark" thing... that is exactly what I want. :)

**Comment by gruijter** [comment]
Let me sink in all this a bit (it is too nice outside today to do Homey stuff anyway).

**Comment by gruijter** [comment]
I'm testing a new flow trigger strategy now:
price is within [1-6] lowest of [2-8] hours before [time]

If it works throughout the night Ill publish as test tomorrow.

**Comment by gruijter** [comment]
Please test v4.3.3 For more explanation and discussion see
https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/629

**Comment by gruijter** [comment]
No feedback?

**Comment by Wouter-Berman** [comment]
I am testing with the cheapest X hours of the day but am getting a strange result. I am using the following flow:
https://homey.app/f/CftK56/
Which includes two notifications for "one of x cheapest hours" and "not one of X cheapest hours".
And I am receiving both notifications at the same time...

**Comment by gruijter** [comment]
That has nothing to do with the app, but is caused by the way Homey Flows work. The 'then-else' only works based on a 'then' card. So the else in your example is useless :)

**Comment by Wouter-Berman** [comment]
LOL. Thanks for bringing that to my attention. Seems to be working fine.
For the other scenario 12 hours is still not enough for me. I understand the dilemma though. Depending on the selected end-time you have to deal with a different availability of price info. If prices are available between 14:00 and 15:00 you have 24 hours of price info available between 15:00 and 23:00 and 9 hours to 23 hours between 00:00 and 14:00.
A possibility would just be to add a trigger card "The cheapest xx hours before yy" which would just be for the current day and easy to understand for end users. In that situation you always know you have all price info available. And the hours between 17:00 and 23:00 are almost always more expensive anyway. Such a trigger card would complement the trigger card of the xx lowest of [2-12] hours before [time] which can handle the car charging scenario during the night.

**Comment by gruijter** [comment]
I already added the card cheapest XX hours today. I am using that myself in combination with cheapest XX (12) hours before 7am to charge my car. It does make it a bit more complex to setup, but as you noted it is caused by how price data is made available.

Adding another card cheapest XX hours before YY but only for today does not add any value imo, and is only confusing app users to select the correct flow card when creating a flow. So I will leave it as it is.

But thanks for all your input! Much appreciated :)
