### ISSUE TITLE
Daily usage totalizer

### ISSUE THREAD

**Issue by Vetjes** [gruijter/com.gruijter.powerhour#8]
This is really a great app. Combined with 'Insights' showing the totals of 'previous day' creates great insight in power consumption. The only metric I miss is a total for the current day. If I put the 'previous day' totals in Insights then I'm always one day off, so my usage of Wednesday shows on Thursday. A metric for 'day total' would show a real usage. It could just be a copy of the value of 'previous day' but then shifted in time...
As you see in the picture, the consumption showing Jun23 really happened June 22nd, and Jun24 really happened June 23rd.
![image](https://user-images.githubusercontent.com/86045790/124228236-3332f480-db0c-11eb-86a5-56c380f69d4e.png)

**Comment by gruijter** [comment]
The metric total_today is already available for use in flows, but it is not stored in Insights. That is because the today total is constantly changing untill midnight. So what would be the sense of having that in Insights?

So yes, the totals are always shifted a day, a month and a year. That is how time works. I cannot predict the total of a day before the day is over.... And Homey Insights does not allow to shift recorded insights after the fact.

Can you explain more how you want to use todays total? Again: If you want to use it in a flow, you can do that already. If it is only for reporting function, then there is no other way than to take the value at midnight (which means always from the previous day...)

**Comment by Vetjes** [comment]
I see your point. To analyze consumption afterward, if the total_today was visible in Insights as a metric like the total_previousday, then the numbers would match on the day that the energy was used. It's not for use in a flow. 
I know it's not fair to compare, but it should be like the reports of slimmemeterportal or the energy companies.
Anyhow, you've made a great app!

**Comment by gruijter** [comment]
> I know it's not fair to compare, but it should be like the reports of slimmemeterportal or the energy companies.

I created the app out of frustration that Homey does not provide advanced reporting and graphs. But the app is still severely limited by what Homey Insights can do. I'm using enelogic as cloud based energy manager myself. Maybe you can have a loom at that.

Closing the issue now. Thx for your feedback!
